package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.sinosoft.organization.domain.PersonInfo;

public final class portal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(3);
    _jspx_dependants.add("/prototype/link/baseLink.jsp");
    _jspx_dependants.add("/prototype/link/cmpLink.jsp");
    _jspx_dependants.add("/prototype/link/modularLink.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	String basePath = request.getContextPath();
	if(basePath != null && "/".equals(basePath)){
		basePath = "";
	}

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extlib/resources/css/ext-all.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/style/ext-patch.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/style/ext-customer.css\" />\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extlib/adapter/ext/ext-base-debug.js\"></script>\r\n");
      out.write(" <script src=\"");
      out.print(basePath);
      out.write("/publicresource/extlib/ext-all-debug.js\"></script>\r\n");
      out.write("<!-- 汉化文件 -->\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("/publicresource/extlib/ext-lang-zh_CN.js\"></script>\r\n");
      out.write("<!-- <script src=\"");
      out.print(basePath);
      out.write("/publicresource/extlib/ext-all.gzjs\"></script>  -->\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 引入用户登录信息记录对应js -->\r\n");
      out.write("\t<!--打印功能-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/js/LodopFuncs.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/authority/login/login.js\"></script>\r\n");
      out.write("\t<!-- 日期时间工具类，返回常用格式的日期或时间 -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/js/DateTimeTool.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--关闭菜单插件 -->\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.TabCloseMenu/Ext.ux.TabCloseMenu.js\"></script>\r\n");
      out.write("\t<!--基础列表组件 -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.CollectGrid/css/Ext.ux.grid.CollectGrid.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.media/Ext.ux.media.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.RowExpanderGrid/css/Ext.ux.grid.RowExpanderGrid.css\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.GridSummary/Ext.ux.grid.GridSummary.css\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.BatchGrid/Ext.ux.grid.BatchGrid.css\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.FileUploadField/fileuploadfield.css\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.Timefield/css/Spinner.css\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.SuperGrid/LockingGridView.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.SuperGrid/multiple-sorting.css\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 可编辑的列表复合组件 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.MultiBatchGrid/css/Ext.ux.grid.MultiBatchGrid.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.MultiBatchGrid/Ext.ux.grid.MultiBatchGrid.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.Timefield/css/Spinner.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.Timefield/images/spinner-split.gif\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.Timefield/images/spinner.gif\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" \r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/treegrid/treegrid.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("    href=\"");
      out.print(basePath);
      out.write("/GroupHeaderPlugin/GroupHeaderPlugin.css\"/>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/js/validate.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.CollectGrid/Ext.ux.grid.CollectGrid.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.SuperGrid/Ext.ux.grid.SuperGrid.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.SuperGrid/LockingGridView.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.ExpanderGrid/Ext.ux.grid.ExpanderGrid.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.CollectEditGrid/Ext.ux.grid.CollectEditGrid.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.BatchGrid/Ext.ux.grid.BatchGrid.js\"></script>\t\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.RowExpanderGrid/Ext.ux.grid.RowExpanderGrid.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/rowexpander/RowExpander.js\"></script>\r\n");
      out.write("\t<!-- 浮动提示框组件 jianglu-->\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/levitationmsgbox/Ext.ux.LevitationMsgBox.js\"></script>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/professionalcomponent/Ext.ux.util/Ext.ux.util.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.form.DateTimeField/Ext.ux.form.DateTimeField.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.Timefield/Ext.ux.Timefield.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.FileUploadField/Ext.ux.FileUploadField.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.Timefield/spinnerMod.js\"></script>\t\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.Timefield/Ext.ux.Timefield.js\"></script>\t\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/treegrid/TreeGridSorter.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/treegrid/TreeGridColumnResizer.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/treegrid/TreeGridNodeUI.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/treegrid/TreeGridLoader.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/treegrid/TreeGridColumns.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/treegrid/TreeGrid.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/GroupHeaderPlugin/GroupHeaderPlugin.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.media/Ext.ux.media.js\"></script>\r\n");
      out.write("   <!-- 添加 ObjectCombox组件-->\r\n");
      out.write("   <!-- 通用combobox组件 -->\r\n");
      out.write("   <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.plugins.WindowDrawer/Ext.ux.plugins.WindowDrawer.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/professionalcomponent/Ext.ux.combo.ObjectCombox/Ext.ux.combo.ObjectCombox.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 码表combobox -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/professionalcomponent/Ext.ux.combo.SystemCode/Ext.ux.combo.SystemCode.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 码表树形 combobox -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/professionalcomponent/Ext.ux.combo.SystemCode/Ext.ux.combo.ObjectTreeCombox.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.form.pinyinComboBox/Ext.ux.form.PinyinFilter.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.grid.GridSummary/Ext.ux.grid.GridSummary.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.form.SpinnerField/Ext.ux.form.SpinnerField.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.Timefield/Ext.ux.Timefield.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.Timefield/spinnerMod.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.Spinner/Ext.ux.Spinner.js\"></script>\r\n");
      out.write("    <!-- 分步加载树组件 -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/jsontree/Ext.lingo.JsonTree.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/jsontree/Ext.lingo.StepLoadTree.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/treegrid/ScrollTreeGridLoader.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/treegrid/StepLoadTreeGrid.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.MonthPickerPlugin/Ext.ux.MonthPickerPlugin.js\"></script>\r\n");
      out.write("\t    <!-- 高级搜索ComboBox -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/extjscomponent/Ext.ux.combo.AdvancedSearchCombo/Ext.ux.combo.AdvancedSearchCombo.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/professionalcomponent/Ext.ux.combo.Organization/Ext.ux.combo.Organization.OrganTreeWindow.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/professionalcomponent/Ext.ux.combo.Organization/Ext.ux.combo.Organization.OrganTreePanel.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/professionalcomponent/Ext.ux.combo.Organization/Ext.ux.combo.Organization.OrganTreeCombo.js\"></script>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--jsp引入 菜单 -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menu/Menu.Validate.js\"></script>\r\n");
      out.write("\t<script rel=\"stylesheet\" type='text/css' src=\"");
      out.print(basePath);
      out.write("/menu/Ext.ux.IconCombo.css\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("/menu/Ext.ux.plugins.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menu/Menu.EditSystemWindow.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menu/Menu.EditButtonWindow.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menu/Menu.EditMenuWindow.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menu/Menu.AddSystemWindow.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menu/Menu.AddMenuWindow.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menu/Menu.AddButtonWindow.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menu/Menu.Variables.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menu/MenuTree.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--  公共变量 -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menuGroup/Menu.Group.Variables.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menuGroup/Menu.Group.Methods.js\"></script>\r\n");
      out.write("\t<!--  结束 -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menuGroup/Menu.Group.AllMenuTree.js\"></script>\r\n");
      out.write("<!-- \r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menuGroup/Menu.Group.AddMenuGroupBaseInfoWindow.js\"></script>\r\n");
      out.write(" -->\r\n");
      out.write("    <!-- 菜单分组 -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menuGroup/Menu.Group.AddMenuGroupTree.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menuGroup/Menu.Group.AddMenuTree.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menuGroup/Menu.Group.AddMenuGroupWindow.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menuGroup/Menu.Group.EditMenuTree.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menuGroup/Menu.Group.EditMenuGroupWindow.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menuGroup/Menu.Group.MenuGroupGrid.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menuGroup/Menu.Group.MenuGroupView.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menuGroup/Menu.Group.SetMenuGroupStructWindow.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/menuGroup/MenuGroup.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--jsp引入数据字典 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/systemcode/Systemcode.SystemcodePanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/systemcode/Systemcode.CodeTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/systemcode/Systemcode.CodeNodeGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/systemcode/Systemcode.CodeTypeWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/systemcode/Systemcode.CodeNodeWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/systemcode/Systemcode.SendCodeWindow.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<!--jsp引入 操作日志组件 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/log/loginLogManager/Log.LoginLogGrid.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/log/loginLogManager/Log.OperationLogGrid.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/log/loginLogManager/Log.OperationDataLogGrid.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/log/loginLogManager/Log.UserLoginLogGrid.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/log/common/Log.Constants.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/log/common/Log.Util.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 组织机构文本框校验文件 -->\r\n");
      out.write("\t\t<!-- 组织机构 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organization/Organization.Validate.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organization/Organization.CopyDeptObjectTreeCombox.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organization/Organization.CopyOrganObjectTreeCombox.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organization/Organization.AddOrganizationWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organization/Organization.AddDeptWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organization/Organization.EditDeptWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organization/Organization.DeptTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organization/Organization.OrganColumnTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organization/organization.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 公共部分 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organUserjs/Organ.User.Variables.js\"></script>\r\n");
      out.write("\t\t<!-- 带客户列表的部门树 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organUserjs/Organ.User.tree.DeptCustomerOrganTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organUserjs/Organ.User.tree.DeptCustomerOrganGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organUserjs/Organ.User.tree.DeptCustomerOrganTreeCombo.js\"></script>\r\n");
      out.write("\t\t<!--  结束 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organUserjs/Organ.User.DeptTree.js\"></script>\r\n");
      out.write("\t\t<!-- 用于处理机构拆分的文件 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organUserjs/Organ.User.ObjectTreeCombox.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organUserjs/Organ.User.AddOrganPersonWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organUserjs/Organ.User.EditOrganPersonWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organUserjs/Organ.User.ShowOrganPersonWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organUserjs/Organ.User.ShowOrganWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organUserjs/Organ.User.organUserColumnTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organUserjs/organUser.js\"></script>\r\n");
      out.write("\t\t<!-- 结束 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 机构分组 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organGroup/Organ.Group.Variables.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organGroup/Organ.Group.editOrganGroupPersonGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organGroup/Organ.Group.editDeptTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organGroup/Organ.Group.editOrganGroupWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organGroup/Organ.Group.addOrganGroupPersonGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organGroup/Organ.Group.addDeptTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organGroup/Organ.Group.addOrganGroupWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organGroup/Organ.Group.organGroupGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/organGroup/organGroup.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 权限设置 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.AuthorityMenuTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.ShowAuthorityMenuTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.AuthorityDataGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.RoleListGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.UserListGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.RoleWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.ConfigAuthorityWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.AuthorityDeptTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.OrganTreeCombox.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.AuthorityDatabaseTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.AuthorityConfigPanel.js\"></script>\r\n");
      out.write("\t  <!-- 权限分配 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.AuthorityAssignPanel.js\"></script>\r\n");
      out.write("\t  <!-- 权限查看 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.QueryAuthorityRoleListGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.QueryAuthorityUserListGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.QueryAuthorityDeptTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.QueryConfigAuthorityWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.QueryConfigAuthorityMenuTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.QueryConfigAuthorityDeptTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.QueryConfigUserListGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.ShowUserAuthorityWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.ShowUserAuthorityMenuTree.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.AuthorityViewPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.QueryAuthorityDeptRoleListGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/authority/Authority.QueryAuthorityUserRoleListGrid.js\"></script>\r\n");
      out.write("\t  <!-- 结束 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 测试pagebar的统计功能 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/Test/TestPagebar.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 公共信息查看 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/commonSearch/comMainPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/commonSearch/comRoadLoadGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/commonSearch/comRoadUnloadGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/commonSearch/comSpecialGrid.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/InvoiceTypeSetManager/invoiceSetGrid.js\"></script>\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/InvoiceTypeSetManager/invoiceSetWin.js\"></script>\t\t\r\n");
      out.write("\t\t<!-- 专用车管理组件开始 -->\r\n");
      out.write("\t\t<!-- 自备车更改代码开始 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/checkManager/checkGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/checkManager/auditInputGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/checkManager/cheifWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/checkManager/cheifAudit.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/checkManager/pointCustomers.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/loadPersonInput/formPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/loadPersonInput/inputCarMessage.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/loadPersonInput/loadPersonGrid.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/goodAdjuestPerson/BatchInputWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/goodAdjuestPerson/ownedCarsMesGrid.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/unloadPersonInput/emptyDateWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/unloadPersonInput/unLoadAllDateWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/unloadPersonInput/loadDateWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/OwnedCarsManger/unloadPersonInput/unloadPersonGrid.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/outPutMessage/dealLog.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/outPutMessage/dealMessage.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/outPutMessage/outPutMainPanel.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 结算管理组件结束 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 客商管理注册组件 -->\r\n");
      out.write("\t\t<!-- 协议客商信息 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/sellComp/ownedComp.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/sellComp/roadLoadComp.js\"></script>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/sellComp/roadUnloadComp.js\"></script>\r\n");
      out.write("\t\t<!-- 协议模块 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/sellManager/addSellWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/sellManager/sellGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/sellManager/addFeeWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/sellManager/addFeeGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/sellManager/addMainMes.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/sellManager/sellMainPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/sellManager/sellFeeGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/sellManager/changeFeeGrid.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 费率管理 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/baseRateManager/ratesManagerGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/baseRateManager/addBaseFeeWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/rateManager/rateMain.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/rateManager/rateGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/rateManager/rateAddWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/rateManager/changeRateWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/rateManager/feeManagerGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/rateManager/rateHistoryGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/customerManagement/rateManager/rateHistoryWin.js\"></script>\r\n");
      out.write("\t\t<!-- 发票变更模块 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 资金管理模块定义 -->\r\n");
      out.write("\t\t<!-- 客商管理 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/fundManager/customerManager/addCustomerWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/fundManager/customerManager/managerCustomer.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/fundManager/customerManagerAdd/managerCustomerAdd.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/fundManager/customerManagerAdd/customerAddInfoWin.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 资金管理 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/fundManager/fundManager/fundManager.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/fundManager/fundManager/InputMoneyWin.js\"></script>\r\n");
      out.write("\t\t<!-- 会计管理模块 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/balanceManager.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/billManager.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/billWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/billDetail.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/goodsManager.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/inventoryManager.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/CarWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/billTabMainPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/inventDetail.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/inventWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/signTabMainPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/signFeetList.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/InventTabMainPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/signformManager.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/signWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/signDetail.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/standard.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/tallyManager.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/tallyDetail.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AccountingManager/balanceSearch/tallyWin.js\"></script>\r\n");
      out.write("\t\t<!-- 货延费管理 -->\r\n");
      out.write("\t\t<!-- lxt add begin 2013.10.08 -->\r\n");
      out.write("\t\t<!-- 共管费管理 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/transportFee/condominiumFee/condominiumFeeGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/transportFee/condominiumFee/addCondominiumWin.js\"></script>\r\n");
      out.write("\t\t<!-- 货延费管理 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/transportFee/goodsDelayFee/goodDelayFee.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/transportFee/goodsDelayFee/addGoodsDelayFeeWin.js\"></script>\r\n");
      out.write("\t\t<!-- 超编载费管理 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/transportFee/overLoadFee/overLoadFeeGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/transportFee/overLoadFee/addOverLoadFeeWin.js\"></script>\r\n");
      out.write("\t\t<!-- 货延费汇总 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/transportFee/goodsDelayStatistics/goodsDelayStatisticsGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/transportFee/scaleTestingFee/scaleTestingFeeGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/transportFee/scaleTestingFee/scaleTestingFeeGridWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/transportFee/otherFeeManager/otherFeeManagerGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/transportFee/otherFeeManager/otherFeeWin.js\"></script>\r\n");
      out.write("\t\t<!-- 路用车管理模块 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInput/unloadInputGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAudit/unloadAuditEditWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAudit/unloadAuditChangeWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAudit/unloadAuditInputGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAudit/auditChangeInputGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAdd/unloadInputAddGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAdd/unloadInputWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAdd/callInTimeInputWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAdd/emptyTimeInputWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAdd/loadLineInputWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAdd/turnOutInputWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAudit/unloadAuditGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/chiefAudit/unloadAuditGrid.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/load/loadInputGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/load/loadSearchGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/load/loadInfoEditWinForPD.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/load/loadMainPanel.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/stopRegister/stopRegistTabMainPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/stopRegister/stopRegistMainPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/stopRegister/stopRegistReachGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/stopRegister/stopRegistLeaveGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/stopRegister/stopRegistLeaveGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/stopRegister/stopRegistLeaveGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAddAudit/addAuditGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAddAudit/addAuditEditWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAddAudit/addAuditChangeWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/unloadInputAddAudit/addAuditInputGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/RoadVehiclesManager/chiefAudit/auditEditWin.js\"></script>\r\n");
      out.write("\t\t<!-- 审核管理 开始-->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AuditManager/loadAudit/loadAuditMainPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AuditManager/loadAudit/loadAuditInputGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/AuditManager/loadAudit/loadAuditEditWin.js\"></script>\r\n");
      out.write("\t\t<!-- 审核管理结束-->\r\n");
      out.write("\t\t<!-- 货调员录入开始-->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtunloadInput/gtunloadInputTabMainPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtunloadInput/gtunloadInputForPD.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtunloadInput/gtunloadInputForPX.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtunloadInput/gtunloadInputGridForPD.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtunloadInput/gtunloadSearchGridForPD.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtunloadInput/gtunloadInputGridForPX.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtunloadInput/gtunloadSearchGridForPX.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/gtloadInputTabMainPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/gtloadInputForPD.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/gtloadInputForPX.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/gtloadInputTheThirdForPD.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/gtloadInputTheThirdForPX.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/gtinputGridForPD.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/gtinputGridForPX.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/gtinputGridTheThirdForPD.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/gtinputGridTheThirdForPX.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/gtinputSearchGridForPD.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/gtinputSearchGridForPX.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/gtinputSearchGridTheThirdForPD.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/gtinputSearchGridTheThirdForPX.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtloadInput/loadInfoEditWinForPD.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtownedCarsInput/gtownedCarsInputMainPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtownedCarsInput/gtownedCarsInputGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/GoodsTransferPersonInputManager/gtownedCarsInput/gtownedCarsSearchGrid.js\"></script>\r\n");
      out.write("\t\t<!-- 货调员录入结束-->\r\n");
      out.write("\t\t<!-- 结算管理 -->\r\n");
      out.write("\t\t<!-- 清单管理-路用车装车清单 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/InventorysManager/loadInventory/loadInventoryTabMainPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/InventorysManager/loadInventory/inventoryInfo.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/InventorysManager/loadInventory/tickets.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/InventorysManager/loadInventory/inventoryNumWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/InventorysManager/loadInventory/inventoryDetail.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/InventorysManager/loadInventory/freightList.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/InventorysManager/loadInventory/ticketItems.js\"></script>\r\n");
      out.write("\t\t<!-- 清单管理-路用车卸车清单 -->\r\n");
      out.write("\t\t<!-- 发票清单管理-发票管理 -->\r\n");
      out.write("\t\t<!-- 发票清单管理-发票复核-->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/invoiceInventory/invoiceReview/invoiceReview.js\"></script>\r\n");
      out.write("\t\t<!-- 发票清单管理-发票合并-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/invoiceInventory/invoiceCombine/invoiceDetailWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/invoiceInventory/invoiceCombine/invoCusMesWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/invoiceInventory/invoiceCombine/invoiceCombineTabPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/invoiceInventory/invoiceCombine/InvoiceCars.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/invoiceInventory/invoiceCombine/InvoiceCarsWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/invoiceInventory/invoiceCombine/invoiceDetail.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/invoiceInventory/invoiceCombine/invoiceInfo.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/invoiceInventory/invoiceCombine/specialWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/invoiceInventory/invoiceCombine/invoiceNumWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/invoiceInventory/invoiceCombine/invoiceSplit.js\"></script>\r\n");
      out.write("\t\t<!-- 发票清单管理-签收单管理-->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signatureformManager/mainGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signatureformManager/mainGridPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signatureformManager/signWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signatureformManager/ticketMainGridPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signatureformManager/billCode.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signatureformManager/addInfoWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signatureformManager/goodFeeCode.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signatureformManager/totalManagerCode.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signManager/signManPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signatureformManager/LocomotiveFeeGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signatureformManager/otherFeeGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signManager/signMes.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signatureformManager/trackFeeGrid.js\"></script>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signatureformManager/scaleTestFeeSignGrid.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signManager/goFeeGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signManager/LocFeeGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signManager/othFeeGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signManager/scaleTestFeeGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signManager/signMainGridPanel.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signManager/totManCode.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/signManager/traFeeGrid.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/accountManager/signManager.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 结算管理-记账-->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/BookKeeping/BookKeepSignatureForm.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/BookKeeping/BookDetail.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/BookKeeping/BookKeepWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SettlementManager/BookKeeping/bookKeppingWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SpecialManager/addSpecialManagerWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SpecialManager/addOthSpecialManagerWin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/prototype/SpecialManager/orgSpeManGrid.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("\t\t<link rel=\"SHORTCUT ICON\"\r\n");
      out.write("\thref=\"");
      out.print(basePath);
      out.write("/publicresource/images/favicon.ico\"/>\r\n");
      out.write("\t\t<title>中国神马集团铁路运输处货运调度系统</title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link href=\"/publicresource/style/css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/publicresource/professionalcomponent/Ext.ux.CursorFollowTip/Ext.ux.CursorFollowTip.js\"></script>\r\n");
      out.write("\t\t");

			String menuImport = (String)request.getAttribute("menuImport");
		
      out.write("\r\n");
      out.write("\t\t");
      out.print( menuImport);
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../publicresource/js/System.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../publicresource/js/System.security.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../publicresource/js/System.Accordion.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../publicresource/js/System.PswWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../publicresource/js/System.centerTabPanel.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 升级后的日志组件 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/system/logManager/historyUserLog.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/system/logManager/currentLogState.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/system/logManager/Log.LogListenerWindow.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/system/logManager/timelimit/timelimit.grid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/system/logManager/timelimit/timeLimitOperationLogDetail.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/system/logManager/extlog/logOperationgrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/system/logManager/extlog/logDataOperationGrid.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/system/logManager/extlog/sinosoft_log.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 引入权限session的js -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/publicresource/js/AuthorityUserConfig.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<SCRIPT LANGUAGE=\"Javascript\" SRC=\"../publicresource/js/FusionCharts.js\"></SCRIPT>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");

PersonInfo personInfo = (PersonInfo)session.getAttribute("person");
String userCname = "",userId = "";
if(personInfo != null){
	userCname = personInfo.getUserCname();
	userId = personInfo.getId();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tSystem.cache.setCacache(Ext.decode(\"");
      out.print((String)request.getAttribute("jsInfoStr"));
      out.write("\"));\r\n");
      out.write("\tSystem.userInfo.setUserJsonInfo(Ext.decode(\"");
      out.print((String)request.getAttribute("userInfoStr"));
      out.write("\"));\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onLoad=\"\">\r\n");
      out.write("\t\t<input id=\"userCname\" type=\"hidden\" value=\"");
      out.print(userCname);
      out.write("\"></input>\r\n");
      out.write("\t\t<input id=\"userId\" type=\"hidden\" value=\"");
      out.print(userId);
      out.write("\"></input>\r\n");
      out.write("\t\t<div id=\"loading-mask\" style=\"\"></div>\r\n");
      out.write("\t\t<div id=\"loading\">\r\n");
      out.write("\t\t\t<div class=\"loading-indicator\">\r\n");
      out.write("\t\t\t\t<img src=\"/publicresource/images/icons/animate/loading-balls.gif\" style=\"margin-right: 8px;\" align=\"absmiddle\" />\r\n");
      out.write("\t\t\t\t加载数据中...\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"nav_area\" class=\"x-hide-display\"></div>\r\n");
      out.write("\t\t<!-- use class=\"x-hide-display\" to prevent a brief flicker of the content -->\r\n");
      out.write("\t\t<div id=\"west\" class=\"x-hide-display\"></div>\r\n");
      out.write("\t\t<div id=\"center2\" class=\"x-hide-display\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
